site_name: FlexHex Rose-ap
site_url: https://github.com/Factobotics/FlexHex-Rose-AP
repo_url: https://github.com/Factobotics/FlexHex-Rose-AP
site_description: FlexHex Rose-ap
docs_dir: docs
site_dir: html
edit_uri: blob/master/docs/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: material
pages:
  - Home: 'index.md'
  - 'Installation Guide': 
    - 'Installation Guide': 'installationguide.md'
  - 'User manuals':
    - 'Getting Started Guide' : 'getting-started.md'
    - 'Step-by-step Guide' : 'step-by-step.md'
  - 'Architecture and API documentation':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'

