site_name: <site-name>
site_url: https://<site-url>
repo_url: https://github.com/Factobotics/FlexHex-Rose-AP
site_description: FlexHex Rose-ap
docs_dir: docs
site_dir: html
edit_uri: edit/master/doc/
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
pages:
  - Home: 'index.md'
  - 'Getting Started' : 'getting-started.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
    - 'Step-by-step Guide': 'step-by-step.md'
  - 'Installation Manual': 
    - 'Installation Guide': 'installationguide.md'
